language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t beltonp/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true beltonp/docker-react npm run test
